Added Cross Ange, Girls Bravo, Juden Chan, KanColle: Kantai Collectio…
mizz141/PlexAniSync-Mappings pull request #76
Opened 2023-01-24 08:43 UTC by DexLuther

…n and Million Arthur

- Added Cross Ange: https://anilist.co/anime/20806/Cross-Ange-Rondo-of-Angel-and-Dragon/
- Added Girls Bravo: Season 1: https://anilist.co/anime/241/Girls-Bravo/  Season 2: https://anilist.co/anime/487/Girls-Bravo-Second-Season/
- Added Juden Chan: https://anilist.co/anime/5973/Juden-Chan/
- Added KanColle: Kantai Collection:  Season 1: https://anilist.co/anime/20553/KanColle/ Season 2: https://anilist.co/anime/21294/KanColle-Season-2-Lets-Meet-at-Sea/
- Added Million Arthur:
    Season 1: https://anilist.co/anime/101359/Million-Arthur/
    Season 2: https://anilist.co/anime/104071/Million-Arthur-2/

2023-01-24 20:40 UTC, mizz141 requested changes

2023-01-24 20:40 UTC, mizz141 commented on custom_mappings.yaml
> +      - "Cross Ange: Rondo of Angels and Dragons"
add more synonyms:

`- "Cross Ange: Tenshi to Ryuu no Rondo"`

2023-01-24 20:40 UTC, mizz141 commented on custom_mappings.yaml
> +      - "KanColle: Kantai Collection"
```
    synonyms:
      - "KanColle: Let's Meet at Sea" 
      - "KanColle - Fleet Girls Collection -"
      - "Kantai Collection: KanColle"
```

2023-01-24 20:40 UTC, mizz141 commented on custom_mappings.yaml
> +      - "Charger Girl Juden Chan"
```
    synonyms:
      - "Fight Ippatsu! Juuden-chan!!"
      - "Fight Ippatsu! Jūden-chan!!"
      - "Fight, One Shot! Charger Girls!!"
      - "Charger Girl Ju-den Chan"
```

2023-01-24 20:40 UTC, mizz141 commented on custom_mappings.yaml
> +      - "Operation Han-Gyaku-Sei Million Arthur"
```
    synonyms:
      - "Han-Gyaku-Sei Million Arthur"
      - "Hangyakusei Million Arthur"
```

2023-01-24 20:41 UTC, mizz141 commented
Hello, thank you for taking your time to contribute to this project, I've requested some additional synonyms to be added before I can go ahead and merge your PR.

2023-01-26 17:04 UTC, DexLuther commented
> Hello, thank you for taking your time to contribute to this project, I've requested some additional synonyms to be added before I can go ahead and merge your PR.

I think I updated it. Not really used to using Github, so not sure if I did it right or if it worked. lol

2023-01-26 17:05 UTC, mizz141 approved these changes

2023-01-26 17:06 UTC, mizz141 commented
> > Hello, thank you for taking your time to contribute to this project, I've requested some additional synonyms to be added before I can go ahead and merge your PR.
> 
> I think I updated it. Not really used to using Github, so not sure if I did it right or if it worked. lol

The github action ran through without issue, so you did everything right on that side, I'll merge the commit and it should be live next time you run the script.

2023-01-26 17:06 UTC, merged

2023-01-26 17:07 UTC, mizz141 commented
Also you might want to look into your github settings and change your commit address since it's leaking your email: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address